language: erlang
sudo: false

os: linux
otp_release:
  - 21.2.6
  - 20.0

matrix:
  include:
    - os: linux
      otp_release: 19.3
    - os: linux
      otp_release: 20.0
    - os: linux
      otp_release: 21.2.6

cache:
  directories:
    - node_modules

before_script:
  - make rebar
  - nvm install 6.2 && nvm use 6.2
  - npm install

script:
  - npm run flow
  - CI=true npm run test
  - make compile && rm -rf .git && make test
